export const ACCOUNT_CREATE_REQUEST = 'ACCOUNT_CREATE_REQUEST'
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS'
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL'
export const ACCOUNT_CREATE_RESET = 'ACCOUNT_CREATE_RESET'

export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST'
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
export const DEPOSIT_FAIL = 'DEPOSIT_FAIL'
export const DEPOSIT_RESET = 'DEPOSIT_RESET'

export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST'
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS'
export const WITHDRAW_FAIL = 'WITHDRAW_FAIL'
export const WITHDRAW_RESET = 'WITHDRAW_RESET'

export const TRANSFER_REQUEST = 'TRANSFER_REQUEST'
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS'
export const TRANSFER_FAIL = 'TRANSFER_FAIL'
export const TRANSFER_RESET = 'TRANSFER_RESET'

export const BALANCE_REQUEST = 'BALANCE_REQUEST'
export const BALANCE_SUCCESS = 'BALANCE_SUCCESS'
export const BALANCE_FAIL = 'BALANCE_FAIL'
export const BALANCE_RESET = 'BALANCE_RESET'

